import { describe, it, expect } from 'vitest';
import {
  areaOf,
  buildSmartDiff,
  classifyFile,
  findingsForFile,
  looksGenerated,
  suggestSplit,
  wiringShare,
  type DiffFileInput,
} from '../src/modules/smart-diff/helpers.js';

const file = (path: string, patch: string | null = '@@ -1,1 +1,2 @@\n x\n+const y = compute(x);', additions = 1, deletions = 0): DiffFileInput => ({
  path,
  additions,
  deletions,
  patch,
});

describe('classifyFile', () => {
  it.each([
    ['server/pnpm-lock.yaml', 'lockfile'],
    ['server/src/db/migrations/meta/0012_snapshot.json', 'generated'],
    ['client/src/a/__snapshots__/Card.test.tsx.snap', 'generated'],
    ['server/test/fixtures/pr.json', 'test'],
    ['client/src/a/Card.test.tsx', 'test'],
    ['docs/labs/lab-03.md', 'docs'],
    ['client/messages/en/prReview.json', 'i18n'],
    ['pr-assets/shot.png', 'assets'],
    ['client/src/a/_components/Card/styles.ts', 'styles'],
    ['server/package.json', 'tooling'],
    ['client/vitest.config.ts', 'tooling'],
    ['server/.dependency-cruiser.cjs', 'tooling'],
    ['server/src/db/migrations/0012_superb_nighthawk.sql', 'migration'],
    ['.github/workflows/ci.yml', 'infra'],
    ['server/src/modules/index.ts', 'entrypoint'],
    ['server/src/platform/config.ts', 'config'],
    ['server/src/modules/reviews/intent.ts', 'source'],
  ])('%s → %s', (path, reason) => {
    expect(classifyFile(file(path))).toBe(reason);
  });

  it('calls a source file with no line changes a rename, but keeps a binary asset an asset', () => {
    expect(classifyFile(file('server/src/old-name.ts', null, 0, 0))).toBe('rename');
    expect(classifyFile(file('docs/diagram.png', null, 0, 0))).toBe('assets');
  });

  it('treats a source file whose changes are imports and registrations as wiring', () => {
    const patch = [
      '@@ -1,3 +1,6 @@',
      " import a from './a.js';",
      "+import blast from './blast/routes.js';",
      "+import { x,",
      '+  y } from "./y.js";',
      '   a,',
      '+  blast,',
      '+app.register(blast);',
    ].join('\n');
    expect(classifyFile(file('server/src/modules/registry.ts', patch, 5))).toBe('imports_only');
    // One real statement among the imports keeps it core (2 of 4 = 50% < 60%).
    const mixed = "@@ -1,1 +1,4 @@\n+import a from './a.js';\n+import b from './b.js';\n+const total = a + b;\n+if (total > 10) throw new Error('big');";
    expect(classifyFile(file('server/src/sum.ts', mixed, 4))).toBe('source');
  });

  it('spots a generated banner only at the top of a new file', () => {
    expect(looksGenerated('@@ -0,0 +1,3 @@\n+// @generated by protoc\n+export const a = 1;')).toBe(true);
    expect(looksGenerated('@@ -40,2 +40,3 @@\n a\n+// DO NOT EDIT below\n b')).toBe(false);
    expect(classifyFile(file('server/src/proto/api.ts', '@@ -0,0 +1,2 @@\n+/* Auto-generated. */\n+export {};'))).toBe('generated');
  });
});

describe('wiringShare', () => {
  it('ignores brackets, blank lines and comments, and is null when nothing is left', () => {
    expect(wiringShare(['});', '', '// note', "import a from 'a';"])).toBe(1);
    expect(wiringShare(['}', '  ', '// only a comment'])).toBeNull();
  });
});

describe('findingsForFile', () => {
  it('keeps the file’s findings with a known severity, top to bottom, end never before start', () => {
    const marks = findingsForFile('a.ts', [
      { id: '2', file: 'a.ts', startLine: 30, endLine: 31, severity: 'WARNING', title: 'w' },
      { id: '1', file: 'a.ts', startLine: 10, endLine: 4, severity: 'CRITICAL', title: 'c' },
      { id: '3', file: 'b.ts', startLine: 1, endLine: 1, severity: 'CRITICAL', title: 'other file' },
      { id: '4', file: 'a.ts', startLine: 5, endLine: 5, severity: 'INFO', title: 'unknown level' },
    ]);
    expect(marks.map((m) => [m.id, m.start_line, m.end_line])).toEqual([
      ['1', 10, 10],
      ['2', 30, 31],
    ]);
  });
});

describe('areaOf', () => {
  it('finds the package and the feature folder', () => {
    expect(areaOf('server/src/modules/blast/service.ts')).toEqual({ top: 'server', feature: 'blast' });
    expect(areaOf('client/src/app/repos/[repoId]/pulls/[number]/_components/BlastRadiusCard/BlastTree.tsx')).toEqual({
      top: 'client',
      feature: 'BlastRadiusCard',
    });
    expect(areaOf('client/src/lib/hooks/blast.ts')).toEqual({ top: 'client', feature: 'hooks' });
    expect(areaOf('src/api/users.ts')).toEqual({ top: '', feature: 'api' });
    expect(areaOf('README.md')).toEqual({ top: '', feature: '' });
  });
});

describe('suggestSplit', () => {
  const sized = (path: string, lines: number, role: 'core' | 'wiring' | 'boilerplate' = 'core') => ({ path, role, lines });

  it('counts only core and wiring lines against the limit', () => {
    const split = suggestSplit([sized('server/src/a.ts', 300), sized('server/pnpm-lock.yaml', 5000, 'boilerplate')]);
    expect(split).toEqual({ too_big: false, total_lines: 5300, reviewable_lines: 300, proposed_splits: [] });
  });

  it('splits by package when the PR spans several, folding slivers in after the largest slice’s own files', () => {
    const split = suggestSplit([
      sized('server/src/modules/blast/service.ts', 300),
      sized('server/src/modules/index.ts', 2, 'wiring'),
      sized('client/src/_components/Card/Card.tsx', 200),
      sized('mcp/src/tools/blast.ts', 20),
    ]);
    expect(split.too_big).toBe(true);
    expect(split.proposed_splits).toEqual([
      { name: 'server', files: ['server/src/modules/blast/service.ts', 'server/src/modules/index.ts', 'mcp/src/tools/blast.ts'] },
      { name: 'client', files: ['client/src/_components/Card/Card.tsx'] },
    ]);
  });

  it('splits by feature inside one package, and proposes nothing without a clean cut', () => {
    const twoFeatures = suggestSplit([sized('server/src/modules/blast/a.ts', 250), sized('server/src/modules/intent/b.ts', 250)]);
    expect(twoFeatures.proposed_splits.map((s) => s.name)).toEqual(['server/blast', 'server/intent']);
    const oneFeature = suggestSplit([sized('server/src/modules/blast/a.ts', 450), sized('server/src/modules/blast/b.ts', 50)]);
    expect(oneFeature).toMatchObject({ too_big: true, proposed_splits: [] });
  });
});

describe('buildSmartDiff', () => {
  it('orders groups core → wiring → boilerplate, files with the worst findings first', () => {
    const result = buildSmartDiff(
      [
        file('server/pnpm-lock.yaml', null, 90, 20),
        file('server/src/modules/index.ts', "@@ -1,1 +1,2 @@\n a,\n+b,", 1),
        file('server/src/big.ts', '@@ -1,1 +1,2 @@\n x\n+const y = 1;', 120),
        file('server/src/risky.ts', '@@ -1,1 +1,2 @@\n x\n+fetch(url);', 3),
      ],
      [
        { id: 'f1', file: 'server/src/risky.ts', startLine: 2, endLine: 2, severity: 'CRITICAL', title: 'SSRF' },
        { id: 'f2', file: 'server/src/risky.ts', startLine: 2, endLine: 3, severity: 'WARNING', title: 'no timeout' },
      ],
      { used: 2, stale: false },
    );
    expect(result.groups.map((g) => [g.role, g.files.map((f) => f.path)])).toEqual([
      ['core', ['server/src/risky.ts', 'server/src/big.ts']],
      ['wiring', ['server/src/modules/index.ts']],
      ['boilerplate', ['server/pnpm-lock.yaml']],
    ]);
    const risky = result.groups[0]!.files[0]!;
    expect(risky).toMatchObject({ reason: 'source', finding_lines: [2], pseudocode_summary: null });
    expect(risky.findings.map((f) => f.severity)).toEqual(['CRITICAL', 'WARNING']);
    expect(result).toMatchObject({ reviews_used: 2, markers_stale: false });
    expect(result.split_suggestion).toMatchObject({ too_big: false, total_lines: 234, reviewable_lines: 124 });
  });

  it('omits empty groups, and never calls markers stale when there are none', () => {
    const result = buildSmartDiff([file('docs/a.md')], [], { used: 0, stale: true });
    expect(result.groups.map((g) => g.role)).toEqual(['boilerplate']);
    expect(result.markers_stale).toBe(false);
  });
});
