import type { CSSProperties } from "react";

/** Co-located styles for the agent's Context tab (mirrors the Skills tab). */
export const s = {
  wrap: { maxWidth: 820 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 20, lineHeight: 1.5 } satisfies CSSProperties,
  section: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "0 0 8px",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 24, padding: 0, listStyle: "none" } satisfies CSSProperties,
  row: (dragOver: boolean, dimmed: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 8,
    border: `1px solid ${dragOver ? "var(--accent)" : "var(--border)"}`,
    background: "var(--bg-elevated)",
    opacity: dimmed ? 0.6 : 1,
  }),
  handle: { color: "var(--text-muted)", cursor: "grab", display: "grid", placeItems: "center" } satisfies CSSProperties,
  order: { width: 18, fontSize: 12, color: "var(--text-muted)", textAlign: "right" } satisfies CSSProperties,
  name: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  dir: {
    flex: 1,
    minWidth: 0,
    fontSize: 11.5,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  tokens: { fontSize: 11.5, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  actions: { display: "flex", gap: 2, flexShrink: 0 } satisfies CSSProperties,
  none: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 24 } satisfies CSSProperties,
  filter: { maxWidth: 320, marginBottom: 10 } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  total: (over: boolean): CSSProperties => ({ fontSize: 12, fontWeight: 600, color: over ? "var(--crit)" : "var(--text-secondary)" }),
  footerNote: { marginLeft: "auto", fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
  drawerTitle: { fontSize: 14 } satisfies CSSProperties,
  drawerSub: { display: "inline-flex", alignItems: "center", gap: 10, fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
